main_app/app.py
from flask import Flask
from main_app.blueprints.pages.views import page
from celery import Celery
from main_app.celery_task_registry import CELERY_TASK_LIST
import os


# Extensions
from main_app.extensions import db

def make_celery(app=None):
    """
    Make Celery App
    :param app: flask app instance
    :return: celery
    """

    broker_url = os.getenv('CELERY_BROKER_URL', 'filesystem://')
    broker_dir = os.getenv('CELERY_BROKER_FOLDER', './broker')

    for f in ['out', 'processed']:
        if not os.path.exists(os.path.join(broker_dir, f)):
            os.makedirs(os.path.join(broker_dir, f))

    celery = Celery(app.import_name,
                    broker=broker_url,
                    backend=f"db+{app.config['SQL_ALCHEMY_DATABASE_URI']}")

    celery.conf.update({
        'broker_url': broker_url,
        'broker_transport_options': {
            'data_folder_in': os.path.join(broker_dir, 'out'),
            'data_folder_out': os.path.join(broker_dir, 'out'),
            'data_folder_processed': os.path.join(broker_dir, 'processed')
        },
        'timezone': 'utc',
        'imports': CELERY_TASK_LIST,
        'result_persistent': False,
        'task_serializer': 'json',
        'result_serializer': 'json',
        'accept_content': ['json']})

    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask

    return celery


def create_app(settings_override=None):
    """
    Create a Flask application using the app factory pattern.

    :return: Flask app
    """

    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

    if settings_override:
        app.config.update(settings_override)

    app.register_blueprint(page)

    return app


def extensions(app):
    """
    Register 0 or more extensions (mutates app instance passed in)
    :param app: flask app
    :return: None
    """
    db.init_app(app)

    return None

flask_app = create_app()
celery_app = make_celery(flask_app)

main_app/blueprints/pages/views.py
from flask import current_app as app
from flask import (Blueprint,
                   render_template,
                   request,
                   jsonify)

import sqlite3
import pandas as pd

page = Blueprint('pages', __name__, template_folder='templates')


@page.route("/")
def index():
    """
    Index / Main page
    :return: html
    """

    return render_template('index.html')


@page.route("/_execute_task", methods=['POST'])
def _execute_task():
    """
    Invoke this function from an Ajax Call
    :return: json
    """
    from main_app.blueprints.pages.tasks import my_task

    if request.method == 'POST':
        # Invoke celery task
        task = my_task.delay()

    return jsonify({'taskID': task.id}), 201


@page.route("/celery-results")
def celery_results():
    try:
        conn = sqlite3.connect(app.config['DB_PATH'], detect_types=sqlite3.PARSE_DECLTYPES)

        celery_results_df = pd.read_sql_query('Select * from celery_taskmeta', conn)

        conn.close()

        return render_template('celery-results.html',
                               celery_results=celery_results_df.to_html(classes=["table"],
                                                                        index=False,
                                                                        table_id='celery-results-table'))

    except Exception as err:

        return render_template('celery-results.html',
                               celery_results=None)

main_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>

    <!-- Plotly js -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <!-- Jquery js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 15px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

</style>
</head>
<body>

<div class="sidenav">
    <a href="{{url_for('pages.index') }}">Home</a>
    <a href="{{url_for('pages.celery_results') }}">Celery Results</a>
</div>

<div class="main">
    {% block content %}


    {% endblock %}
</div>

</body>
</html>

main_app/templates/celery-results.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<style>
table {
  border-collapse: collapse;
  font-size:20px;
}

table, td, th {
  border: 1px solid black;
}
</style>
<h2>Example: Execute Task</h2>
<div id="celery-results">
    {{ celery_results | safe }}
</div>




{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}

<h2>Example: Execute Task</h2>
<button id="start-task">Start Task</button><br><br>
<div id="task-message" hidden="true">Task ID Executed: <span id="task-id" ></span></div>



<script>
    $('#start-task').click(function(){
        $.ajax({
            type: 'POST',
            url: '{{url_for('pages._execute_task') }}',
            contentType: 'application/json',
            success:function(data){
                $('#task-id').html(data.taskID);
                $('#task-message').attr('hidden', false);
            }
        })
    });
</script>

{% endblock %}